global:
  namespace: argocd
  project: default
  source:
    repoURL: https://github.com/jonathanfoster/gitops-bridge.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
awsEbsCsiDriver:
  enabled: true
awsLoadBalancerController:
  enabled: true
certManager:
  enabled: true
  crds:
    enabled: true
clusterAutoscaler:
  enabled: true
externalDns:
  enabled: true
externalSecrets:
  enabled: true
ingressNginx:
  enabled: true
metricsServer:
  enabled: true
