global:
  namespace: argocd
  project: default
  source:
    repoURL: https://github.com/jonathanfoster/gitops-bridge.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
certManager:
  enabled: true
  crds:
    enabled: true
ingressNginx:
  enabled: true
kubernetesDashboard:
  enabled: true
metricsServer:
  enabled: true
