---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: add-ons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanfoster/gitops-bridge.git
    targetRevision: HEAD
    path: chart
    helm:
      releaseName: add-ons
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
