apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: add-ons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanfoster/gitops-bridge.git
    targetRevision: main
    path: charts/add-ons
    helm:
      releaseName: add-ons
      values: |
        awsLoadBalancerController:
          clusterName: local
          region: us-east-1
          vpcId: vpc-1234567890abcdef
        ingressNginx:
          controller:
            service:
              type: NodePort
        metricsServer:
          args:
            - --kubelet-insecure-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
